# Generated by Django 2.1.7 on 2019-04-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attendance',
            field=models.BooleanField(default='True'),
        ),
    ]
